language: java

jdk: openjdk8

# before_script: mvn ktlint:check

script: ./gradlew build

# after_success: mvn clean test jacoco:report coveralls:report

notifications:
  email:
    on_success: never
    on_failure: change
